/**
 * **************************************************************
 *    WARNING: DO NOT EDIT THIS FILE.                           *
 *    THIS FILE WAS AUTO-GENERATED ON https://app.zigma.io.     *
 * **************************************************************
 */

var _styleDictionary = {
  "tokens": {
    "colors": {
      "background": {
        "description": "",
        "name": "colors-background",
        "type": "color",
        "value": "#000000",
        "isSource": true,
        "original": {
          "description": "",
          "name": "background",
          "type": "color",
          "value": "#000000"
        },
        "attributes": {
          "category": "colors",
          "type": "background"
        },
        "path": [
          "colors",
          "background"
        ]
      },
      "colors-2": {
        "description": "",
        "name": "colors-colors-2",
        "type": "color",
        "value": "#000000",
        "isSource": true,
        "original": {
          "description": "",
          "name": "colors-2",
          "type": "color",
          "value": "#000000"
        },
        "attributes": {
          "category": "colors",
          "type": "colors-2"
        },
        "path": [
          "colors",
          "colors-2"
        ]
      }
    }
  }
};
