/**
 * **************************************************************
 *    WARNING: DO NOT EDIT THIS FILE.                           *
 *    THIS FILE WAS AUTO-GENERATED ON https://app.zigma.io.     *
 * **************************************************************
 */

var _styleDictionary = {
  "tokens": {
    "spacing": {
      "new-spacing": {
        "description": "",
        "name": "spacing-new-spacing",
        "type": "dimension",
        "value": "0",
        "isSource": true,
        "$extensions": {
          "studio.tokens": {
            "originalType": "spacing"
          }
        },
        "original": {
          "description": "",
          "name": "new-spacing",
          "type": "dimension",
          "value": 0,
          "$extensions": {
            "studio.tokens": {
              "originalType": "spacing"
            }
          }
        },
        "attributes": {
          "category": "spacing",
          "type": "new-spacing"
        },
        "path": [
          "spacing",
          "new-spacing"
        ]
      },
      "spacing-2": {
        "description": "",
        "name": "spacing-spacing-2",
        "type": "dimension",
        "value": "0",
        "isSource": true,
        "$extensions": {
          "studio.tokens": {
            "originalType": "spacing"
          }
        },
        "original": {
          "description": "",
          "name": "spacing-2",
          "type": "dimension",
          "value": 0,
          "$extensions": {
            "studio.tokens": {
              "originalType": "spacing"
            }
          }
        },
        "attributes": {
          "category": "spacing",
          "type": "spacing-2"
        },
        "path": [
          "spacing",
          "spacing-2"
        ]
      },
      "spacing-3": {
        "description": "",
        "name": "spacing-spacing-3",
        "type": "dimension",
        "value": "0",
        "isSource": true,
        "$extensions": {
          "studio.tokens": {
            "originalType": "spacing"
          }
        },
        "original": {
          "description": "",
          "name": "spacing-3",
          "type": "dimension",
          "value": 0,
          "$extensions": {
            "studio.tokens": {
              "originalType": "spacing"
            }
          }
        },
        "attributes": {
          "category": "spacing",
          "type": "spacing-3"
        },
        "path": [
          "spacing",
          "spacing-3"
        ]
      },
      "spacing-4": {
        "description": "",
        "name": "spacing-spacing-4",
        "type": "dimension",
        "value": "0",
        "isSource": true,
        "$extensions": {
          "studio.tokens": {
            "originalType": "spacing"
          }
        },
        "original": {
          "description": "",
          "name": "spacing-4",
          "type": "dimension",
          "value": 0,
          "$extensions": {
            "studio.tokens": {
              "originalType": "spacing"
            }
          }
        },
        "attributes": {
          "category": "spacing",
          "type": "spacing-4"
        },
        "path": [
          "spacing",
          "spacing-4"
        ]
      }
    }
  }
};
