/**
 * **************************************************************
 *    WARNING: DO NOT EDIT THIS FILE.                           *
 *    THIS FILE WAS AUTO-GENERATED ON https://app.zigma.io.     *
 * **************************************************************
 */

var _styleDictionary = {
  "tokens": {
    "typography": {
      "new-typography": {
        "description": "",
        "name": "typography-new-typography",
        "type": "fontFamily",
        "value": "Inter",
        "isSource": true,
        "original": {
          "description": "",
          "name": "new-typography",
          "type": "fontFamily",
          "value": "Inter"
        },
        "attributes": {
          "category": "typography",
          "type": "new-typography"
        },
        "path": [
          "typography",
          "new-typography"
        ]
      }
    }
  }
};
